# Generated by Django 5.2.3 on 2025-08-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_ciudad_customuser_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mascotas_adoptadas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mascotas_publicadas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
