# Generated by Django 5.2.3 on 2025-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_mascotas_adoptadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mascotas_adoptadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mascotas_publicadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
