# Generated by Django 5.2.3 on 2025-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
