# Generated by Django 5.2.3 on 2025-06-18 21:07

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fotos',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='mascotas/'),
        ),
    ]
