# Generated by Django 5.2.3 on 2025-06-18 21:48

import pets.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fotos',
            field=models.ImageField(blank=True, null=True, storage=pets.custom_storages.NoHeadObjectS3Boto3Storage(), upload_to='mascotas/'),
        ),
    ]
