# Generated by Django 5.2.3 on 2025-06-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado')], default='disponible', max_length=20),
        ),
    ]
