# Generated by Django 5.2.3 on 2025-08-14 01:34

import pets.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_adoptionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='url_formulario',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, storage=pets.custom_storages.NoHeadObjectS3Boto3Storage(), upload_to='documentos/adopciones/comprobantes/'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='compromiso_vida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='direccion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='edad',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='ejercicio',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='es_propia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='estado_civil',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='familia_de_acuerdo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='horas_solo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='id_oficial',
            field=models.FileField(blank=True, null=True, storage=pets.custom_storages.NoHeadObjectS3Boto3Storage(), upload_to='documentos/adopciones/ids/'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='mascotas_actuales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='motivo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='protegida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='renta_permite',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='responsable',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='tuvo_mascotas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='vivienda',
            field=models.CharField(default='', max_length=50),
        ),
    ]
