# Generated by Django 5.2.3 on 2025-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_remove_adoptionrequest_url_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
