# Generated by Django 5.2.3 on 2025-09-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_pet_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
