# Generated by Django 5.2.3 on 2025-09-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_adoptionrequest_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='convive_ninos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='convive_otras_mascotas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='es_jugueton',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='es_tranquilo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='nivel_energia',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
    ]
